version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo:4.4.4-bionic
    volumes:
      - ./volumes/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - mongo-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      # ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - mongo-network

networks:
    mongo-network:
      driver: bridge
